In [1]:
from random import seed
from random import random
from math import exp
import pandas as pd
from sklearn.datasets import load_iris
import numpy as np
from sklearn.preprocessing import OneHotEncoder


In [2]:
class Network:
  #konstruktor
  def __init__(self, n_inputs, n_hidden, n_outputs=3):
    self.n_inputs = n_inputs
    self.n_hidden = n_hidden
    self.n_outputs = n_outputs
    
    self.weights_ItoH = np.random.uniform(-1, 1, (n_inputs, n_hidden))
    self.weights_HtoO = np.random.uniform(-1, 1, (n_hidden, n_outputs))
    
    self.dweights_ItoH = np.zeros((n_inputs, n_hidden))
    self.dweights_HtoO = np.zeros((n_hidden, n_outputs))
    
    self.pre_activation_H = np.zeros(n_hidden)
    self.post_activation_H = np.zeros(n_hidden)
    
    self.pre_activation_O = np.zeros(n_outputs)
    self.post_activation_O = np.zeros(n_outputs)
  
  # Calculate net for an input
  def calculate_net_ItoH(self, sample, node):
    return np.dot(self.data[sample,:], self.weights_ItoH[:, node])
  # Calculate net for a hidden unit
  def calculate_net_HtoO(self, node):
    return np.dot(self.post_activation_H, self.weights_HtoO[:, node])

  # Neuron activation
  def activation(self, x):
  	return 1.0/(1 + np.exp(-x))
  
  # Derivation of activation function
  def activation_deriv(self, x):
    return activation(x) * (1 - activation(x))

  def one_hot_encode(self, target):
    encoder = OneHotEncoder(sparse=False)
    new_target = target.reshape(len(target), 1)
    target_encode = encoder.fit_transform(new_target)

  #fit the network to the data
  def fit(self, data, target, epoch_limit=100, mini_batch_limit=10):
    self.data = data
    self.target = self.one_hot_encode(target)
    self.epoch_limit = epoch_limit

    len_data = len(data)

    for epoch in range(epoch_limit):
      
      mini_batch_count = 0
      for instance in range(3):
        # From input layer to hidden layer
        
        ## iterate every hidden layer to fill the values
        for hidden_unit in range(self.n_hidden):
          ### calculate the net input
          self.pre_activation_H[hidden_unit] = self.calculate_net_ItoH(instance, hidden_unit)
          ### calculate the activated value
          self.post_activation_H[hidden_unit] = self.activation(self.pre_activation_H[hidden_unit])

        # From hidden layer to output layer
        for output_unit in range(self.n_outputs):
          ### calculate the net input
          self.pre_activation_O[output_unit] = self.calculate_net_HtoO(output_unit)
          ### calculate the activated value
          self.post_activation_O[output_unit] = self.activation(self.pre_activation_O[output_unit])
      
        #for debug
        print('INSTANCE:', instance )
        print('WEIGHTS\n', self.weights_ItoH, '\n', self.weights_HtoO)
        print('OUTPUTS\n', self.post_activation_H, '\n', self.post_activation_O)

        # Backpropagation
        ## if already at minibatch limit or at the last instance, update the weight 
        if((mini_batch_count == mini_batch_limit) or (instance == len_data - 1)):
          mini_batch_count = 0
        ## if below minibatch limit, update delta-weight
        else:
          #update delta-weight from output
          
          
          #update delta-weight from hidden layer
          mini_batch_count += 1

In [3]:
# Testing
print('Data Iris')
load, target = load_iris(return_X_y=True)
iris_data = pd.DataFrame(load, columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])
iris_data['label'] = pd.Series(target)

net = Network(4, 4)
net.fit(load, target, epoch_limit=1)

Data Iris
INSTANCE: 0
WEIGHTS
 [[-0.86060379 -0.57263416 -0.23529718  0.56293959]
 [-0.88530683 -0.75437421 -0.34978178 -0.20817233]
 [ 0.81519213 -0.20898158  0.01588498  0.7544523 ]
 [ 0.63130405 -0.64220496 -0.72131018  0.00680023]] 
 [[ 0.91570929  0.81372381  0.40482461]
 [ 0.8517756  -0.5952462  -0.28610893]
 [-0.21889323 -0.6185325  -0.88764714]
 [-0.68850269 -0.48786008  0.38546544]]
OUTPUTS
 [0.00198505 0.00251803 0.07267714 0.9608336 ] 
 [0.33771748 0.37435254 0.57589387]
INSTANCE: 1
WEIGHTS
 [[-0.86060379 -0.57263416 -0.23529718  0.56293959]
 [-0.88530683 -0.75437421 -0.34978178 -0.20817233]
 [ 0.81519213 -0.20898158  0.01588498  0.7544523 ]
 [ 0.63130405 -0.64220496 -0.72131018  0.00680023]] 
 [[ 0.91570929  0.81372381  0.40482461]
 [ 0.8517756  -0.5952462  -0.28610893]
 [-0.21889323 -0.6185325  -0.88764714]
 [-0.68850269 -0.48786008  0.38546544]]
OUTPUTS
 [0.00366466 0.00411069 0.08912835 0.9605124 ] 
 [0.33760895 0.37210677 0.57234796]
INSTANCE: 2
WEIGHTS
 [[-0.86060379 -

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [6]:
o = np.random.uniform(1, 10, 3)
j = np.random.uniform(1, 10, 3)
print(o, j)
np.dot(o, j)

[3.11740136 8.27094941 5.9164251 ] [3.51638315 5.36092207 1.32702712]


63.1531494133005

In [10]:
a = np.random.uniform(1,1,(3,5))
b = np.random.uniform(1,10,(3,5))

In [11]:
print(a, '\n')
print(b, '\n')
print(np.add(a,b))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[4.34001615 8.84582444 5.36002125 8.67189147 5.18367231]
 [8.42507471 4.31171515 7.97301027 6.15631649 9.27238015]
 [7.58748903 6.40231917 8.78151948 7.05457473 4.83981053]] 

[[ 5.34001615  9.84582444  6.36002125  9.67189147  6.18367231]
 [ 9.42507471  5.31171515  8.97301027  7.15631649 10.27238015]
 [ 8.58748903  7.40231917  9.78151948  8.05457473  5.83981053]]


In [15]:
a = np.random.uniform(1,1,5)
print(a)
a = np.append(a, 5)
print(a)

[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 5.]
